### ISSUE TITLE
 pip install --pre --upgrade weditor安装失败

### ISSUE THREAD

**Issue by Wing-Li-oceanwing** [openatx/weditor#13]
您好：
我升级weditor之后，安装失败就无法再打开weditor了，如下，请指导，谢谢！

 pip install --pre --upgrade weditor
Collecting weditor
Requirement already up-to-date: six in d:\python27\lib\site-packages (from weditor)
Requirement already up-to-date: futures==3.0.5 in d:\python27\lib\site-packages (from weditor)
Requirement already up-to-date: tornado>=4.3 in d:\python27\lib\site-packages (from weditor)
Collecting atx>=1.1.1.dev47 (from weditor)
  Using cached atx-1.2.1.dev1-py2-none-any.whl
Requirement already up-to-date: singledispatch in d:\python27\lib\site-packages (from tornado>=4.3->weditor)
Requirement already up-to-date: backports-abc>=0.4 in d:\python27\lib\site-packages (from tornado>=4.3->weditor)
Requirement already up-to-date: facebook-wda>=0.2.0 in d:\python27\lib\site-packages (from atx>=1.1.1.dev47->weditor)
Requirement already up-to-date: tqdm==4.5.0 in d:\python27\lib\site-packages (from atx>=1.1.1.dev47->weditor)
Requirement already up-to-date: uiautomator2 in d:\python27\lib\site-packages (from atx>=1.1.1.dev47->weditor)
Requirement already up-to-date: aircv==1.4.6 in d:\python27\lib\site-packages (from atx>=1.1.1.dev47->weditor)
Collecting imageio>=1.5 (from atx>=1.1.1.dev47->weditor)
Requirement already up-to-date: maproxy==0.0.12 in d:\python27\lib\site-packages (from atx>=1.1.1.dev47->weditor)
Requirement already up-to-date: PyYAML==3.11 in d:\python27\lib\site-packages (from atx>=1.1.1.dev47->weditor)
Requirement already up-to-date: subprocess32==3.2.7; python_version <= "2.7" in d:\python27\lib\site-packages (from atx>=1.1.1.dev47->weditor)
Requirement already up-to-date: AxmlParserPY==0.0.3 in d:\python27\lib\site-packages (from atx>=1.1.1.dev47->weditor)
Collecting numpy>=1.11.0 (from atx>=1.1.1.dev47->weditor)
  Using cached numpy-1.14.0-cp27-none-win_amd64.whl
Requirement already up-to-date: requests>=2.9.1 in d:\python27\lib\site-packages (from atx>=1.1.1.dev47->weditor)
Collecting colorama>=0.3.7 (from atx>=1.1.1.dev47->weditor)
  Using cached colorama-0.3.9-py2.py3-none-any.whl
Collecting Pillow>=2.7.0 (from atx>=1.1.1.dev47->weditor)
  Using cached Pillow-5.0.0-cp27-cp27m-win_amd64.whl
Requirement already up-to-date: humanize in d:\python27\lib\site-packages (from uiautomator2->atx>=1.1.1.dev47->weditor)

Requirement already up-to-date: progress>=1.3 in d:\python27\lib\site-packages (from uiautomator2->atx>=1.1.1.dev47->weditor)
Requirement already up-to-date: retry>=0.9.2 in d:\python27\lib\site-packages (from uiautomator2->atx>=1.1.1.dev47->weditor)
Requirement already up-to-date: fire in d:\python27\lib\site-packages (from uiautomator2->atx>=1.1.1.dev47->weditor)
Requirement already up-to-date: urllib3<1.23,>=1.21.1 in d:\python27\lib\site-packages (from requests>=2.9.1->atx>=1.1.1.dev47->weditor)
Requirement already up-to-date: idna<2.7,>=2.5 in d:\python27\lib\site-packages (from requests>=2.9.1->atx>=1.1.1.dev47->weditor)
Requirement already up-to-date: chardet<3.1.0,>=3.0.2 in d:\python27\lib\site-packages (from requests>=2.9.1->atx>=1.1.1.dev47->weditor)
Requirement already up-to-date: certifi>=2017.4.17 in d:\python27\lib\site-packages (from requests>=2.9.1->atx>=1.1.1.dev47->weditor)
Requirement already up-to-date: decorator>=3.4.2 in d:\python27\lib\site-packages (from retry>=0.9.2->uiautomator2->atx>=1.1.1.dev47->weditor)
Requirement already up-to-date: py<2.0.0,>=1.4.26 in d:\python27\lib\site-packages (from retry>=0.9.2->uiautomator2->atx>=1.1.1.dev47->weditor)
Installing collected packages: numpy, Pillow, imageio, colorama, atx, weditor
  Found existing installation: numpy 1.13.0
    Uninstalling numpy-1.13.0:
      Successfully uninstalled numpy-1.13.0
  Rolling back uninstall of numpy
Exception:
Traceback (most recent call last):
  File "d:\python27\lib\site-packages\pip\basecommand.py", line 215, in main
    status = self.run(options, args)
  File "d:\python27\lib\site-packages\pip\commands\install.py", line 342, in run
    prefix=options.prefix_path,
  File "d:\python27\lib\site-packages\pip\req\req_set.py", line 790, in install
    requirement.rollback_uninstall()
  File "d:\python27\lib\site-packages\pip\req\req_install.py", line 759, in rollback_uninstall
    self.uninstalled.rollback()
  File "d:\python27\lib\site-packages\pip\req\req_uninstall.py", line 135, in rollback
    renames(tmp_path, path)
  File "d:\python27\lib\site-packages\pip\utils\__init__.py", line 267, in renames
    shutil.move(old, new)
  File "d:\python27\lib\shutil.py", line 302, in move
    copy2(src, real_dst)
  File "d:\python27\lib\shutil.py", line 130, in copy2
    copyfile(src, dst)
  File "d:\python27\lib\shutil.py", line 83, in copyfile
    with open(dst, 'wb') as fdst:
IOError: [Errno 13] Permission denied: 'd:\\python27\\lib\\site-packages\\numpy\\core\\multiarray.pyd'

**Comment by Wing-Li-oceanwing** [comment]
已经解决这个问题了   请关闭！

**Comment by codeskyblue** [comment]
下次自己关
