### ISSUE TITLE
请问ios设备如何使用weditor获取控件呢？

### ISSUE THREAD

**Issue by q88535448** [openatx/weditor#17]
请问ios设备如何使用weditor获取控件呢？有没有详细的配置方法？

**Comment by codeskyblue** [comment]
下拉菜单选择iOS，填入ios的连接地址，点击Connect，然后点击Reload

**Comment by q88535448** [comment]
已解决，非常感谢，一开始以为把uuid放进去

**Comment by bamboo516** [comment]
连接地址是指什么地址？

**Comment by codeskyblue** [comment]
For example: http://127.0.0.1:8100
