### ISSUE TITLE
Samsung S9 can not fill up the screen canvans

### ISSUE THREAD

**Issue by yanqian** [openatx/weditor#27]
steps to reproduce:
1. set up atx-server 
2. start atx-agent in S9
3. start Weditor and input IP to connect to S9

Result:
![image](https://user-images.githubusercontent.com/2221926/45203160-ce98b200-b2ad-11e8-94a1-9709ca94a66d.png)

As comparing, OPPO A160 image below:
![image](https://user-images.githubusercontent.com/2221926/45203204-f851d900-b2ad-11e8-9634-8e78daaf40ab.png)

**Comment by codeskyblue** [comment]
三星手机调整显示分辨率到最大就好了

**Comment by yanqian** [comment]
Correct and  close. Thanks.
