### ISSUE TITLE
你好，我录制的时候连上手机录制，但是无法run，会报这个错

### ISSUE THREAD

**Issue by 541347048** [openatx/weditor#3]
d = atx.connect()
d(text="登录/注册").click()
recv subprocess: 'Traceback (most recent call last):\n'
recv subprocess: '  File "<stdin>", line 3, in <module>\n'
recv subprocess: '  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/atx/__init__.py", line 77, in connect\n'
recv subprocess: '    c = cls(connect_url, **kwargs)\n'
recv subprocess: '  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/atx/drivers/android.py", line 87, in __init__\n'
recv subprocess: '    self._adb_device = self._adb_client.device(serialno)\n'
recv subprocess: '  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/atx/adbkit/client.py", line 130, in device\n'
recv subprocess: '    raise EnvironmentError("Device(%s) not attached." % serial)\n'
recv subprocess: 'EnvironmentError: Device(default) not attached.\n'
Websocket closed

**Comment by 541347048** [comment]
按照报错的字面意思说我没连上设备 但是我已经可以在网页上看到设备监控了  也可以自动输出代码  就是无法run来执行  一执行就报错

**Comment by codeskyblue** [comment]
以修复，请更新weditor
