### ISSUE TITLE
X,Y坐标，Width/Height，Enabled，Visible，XPath属性值获取不到

### ISSUE THREAD

**Issue by holysor** [openatx/weditor#4]
X,Y坐标，Width/Height，Enabled，Visible，XPath属性值获取不到

![ae67fc5e-0f22-4af4-915e-4c1b590390bd](https://user-images.githubusercontent.com/17400810/30366204-e41d0896-989c-11e7-9b7f-c7fea7840484.png)

**Comment by codeskyblue** [comment]
能不能详细点
