### ISSUE TITLE
chrome浏览器界面展示存在问题

### ISSUE THREAD

**Issue by uncleheart** [openatx/weditor#40]
![image](https://user-images.githubusercontent.com/17514361/55564017-982ef280-5729-11e9-80f7-e70bbb779f51.png)
如图所示，获取后，手机界面会展示在下方。当点击一次后会恢复正常。
环境：mac 10.13.6 chrome 73.0.3683.86 
其中使用Safari正常

**Comment by codeskyblue** [comment]
chrome升级下，或许就好了

**Comment by uncleheart** [comment]
=。= 我这已经是最新版本了。浏览器显示为最新版本，我以为会有问题还特意重新下载了

**Comment by codeskyblue** [comment]
那我清明节后再看下。

**Comment by codeskyblue** [comment]
已修复
