### ISSUE TITLE
点击刷新获取页面元素失败

### ISSUE THREAD

**Issue by holysor** [openatx/weditor#5]
WebDriverAgentRunner-Runner[597:202930] Enqueue Failure: Application local.pid.53 is not running /Users/holysor/Desktop/WebDriverAgent/WebDriverAgentRunner/UITestingUITests.m 37 1

**Comment by codeskyblue** [comment]
重启下wda试试？

**Comment by codeskyblue** [comment]
这个问题还是提到facebook/WebDriverAgent吧，这里暂时也解决不了
