### ISSUE TITLE
adbutils.errors.AdbError: device not found

### ISSUE THREAD

**Issue by PikChan** [openatx/weditor#57]
通过weidtor连接，首次能够连接成功，但退出后第二天再启动连接，则提示该错误。
![image](https://user-images.githubusercontent.com/34614146/64916420-3979a480-d7b0-11e9-8721-f490b638d81c.png)

但单独通过uiautomator2可以成功连接，并且成功截图
![image](https://user-images.githubusercontent.com/34614146/64916504-bad13700-d7b0-11e9-8c54-d8f25a517b7f.png)

![image](https://user-images.githubusercontent.com/34614146/64916387-a3457e80-d7af-11e9-90e5-781ff736980d.png)

本人尝试过卸载weditor重装，网上查过多次，资料稀少，成功解决过一次，但不知道是哪些操作解决的。第二天又是老问题。

**查阅过的资料：**
1.  https://www.cnblogs.com/dtting/p/6541392.html
2. https://gitee.com/tp7309/TTEmulatorPortFinder/repository/archive/master.zip

**环境：**
雷电模拟器
win10 64位 
Python3.7.4
![image](https://user-images.githubusercontent.com/34614146/64916413-22d34d80-d7b0-11e9-92f3-4b6ffcead6e3.png)
![image](https://user-images.githubusercontent.com/34614146/64916484-7d6ca980-d7b0-11e9-9929-1d082ebcd4ef.png)

**Comment by PikChan** [comment]
今天终于找到问题所在了，要清除Chrome中该网站上次打开后产生的cookie。但是不知道单独清除网页cookie的方法，不想清理所有，遂作罢。

之前也想到过可能是该原因，但一直以为缓存数据在本地weditor文件夹下的某个文件中。

但实际上，我找过，并没有找到，而且多次卸载（remove相关文件）重装weditor后，仍然不行。

清除cookie后，再connect，成功连接！😄
![image](https://user-images.githubusercontent.com/34614146/65026145-8e611a80-d96a-11e9-8636-47ff418b1f05.png)

![image](https://user-images.githubusercontent.com/34614146/65026029-49d57f00-d96a-11e9-8b1a-5ddcf79d3566.png)

**Comment by codeskyblue** [comment]
weditor的缓存数据是保存在 Chrome的LocalStorage中
